// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WatchWorld.Infrastructure.Database;

#nullable disable

namespace WatchWorld.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914184104_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WatchWorld.Domain.Entities.Borrow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BorrowedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BorrowedFromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Borrows");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.HighResImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<Guid?>("IndividualWatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WatchesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndividualWatchId");

                    b.HasIndex("WatchesId");

                    b.ToTable("HighResImages");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.IndividualWatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WatchesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WearGrade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WatchesId");

                    b.ToTable("IndividualWatches");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IndividualWatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IndividualWatchId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.UserRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RatedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RatingAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RatedByUserId");

                    b.HasIndex("RatedToUserId");

                    b.ToTable("UserRatings");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.Watches", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("BraceletTypeEnum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaseMaterialEnum")
                        .HasColumnType("int");

                    b.Property<int>("CaseShapeEnum")
                        .HasColumnType("int");

                    b.Property<int>("CaseSize")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderEnum")
                        .HasColumnType("int");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovementTypeEnum")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ReleaseYear")
                        .HasColumnType("date");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Watchlist");
                });

            modelBuilder.Entity("WatchWorld.Domain.ValueObjects.ManyToMany.ActiveBorrows", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BorrowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ListingId", "BorrowId");

                    b.ToTable("ActiveBorrows");
                });

            modelBuilder.Entity("WatchWorld.Domain.ValueObjects.ManyToMany.UserOwnsWatch", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WatchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "WatchId");

                    b.ToTable("UserOwnsWatches");
                });

            modelBuilder.Entity("WatchWorld.Domain.ValueObjects.ManyToMany.WatchBorrow", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IndividualWatchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "IndividualWatchId");

                    b.ToTable("WatchBorrows");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.Borrow", b =>
                {
                    b.OwnsOne("WatchWorld.Domain.ValueObjects.TimeSlot", "BorrowTimeSlot", b1 =>
                        {
                            b1.Property<Guid>("BorrowId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("BorrowId");

                            b1.ToTable("Borrows");

                            b1.WithOwner()
                                .HasForeignKey("BorrowId");
                        });

                    b.Navigation("BorrowTimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.HighResImage", b =>
                {
                    b.HasOne("WatchWorld.Domain.Entities.IndividualWatch", null)
                        .WithMany("Picture")
                        .HasForeignKey("IndividualWatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WatchWorld.Domain.Entities.Watches", null)
                        .WithMany("Images")
                        .HasForeignKey("WatchesId");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.IndividualWatch", b =>
                {
                    b.HasOne("WatchWorld.Domain.Entities.Watches", "SpecificWatch")
                        .WithMany()
                        .HasForeignKey("WatchesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SpecificWatch");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.Listing", b =>
                {
                    b.HasOne("WatchWorld.Domain.Entities.IndividualWatch", "BorrowableWatch")
                        .WithMany()
                        .HasForeignKey("IndividualWatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BorrowableWatch");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.UserRating", b =>
                {
                    b.HasOne("WatchWorld.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WatchWorld.Domain.Entities.User", null)
                        .WithMany("Rating")
                        .HasForeignKey("RatedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.IndividualWatch", b =>
                {
                    b.Navigation("Picture");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.User", b =>
                {
                    b.Navigation("Rating");
                });

            modelBuilder.Entity("WatchWorld.Domain.Entities.Watches", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
